anti_detection:
  mouse_movement: true
  random_delay_max: 5
  random_delay_min: 2
  scroll_simulation: true
  typing_delay: true
  user_agent_rotation: true
browser:
  disable_images: true
  disable_javascript: false
  headless: false
  implicit_wait: 10
  page_load_timeout: 30
  user_agent: ''
  window_size:
  - 1920
  - 1080
captcha:
  api_key: ''
  max_retry: 3
  service_provider: 2captcha
  timeout: 120
  use_paid_service: false
faucets:
  0g_testnet:
    captcha_type: image
    cooldown_hours: 24
    name: 0G Testnet Faucet
    network: 0G Testnet
    requires_twitter: true
    requires_wallet: true
    selectors:
      captcha_image: img[src*='captcha'], canvas
      captcha_input: input[placeholder*='captcha'], input[placeholder*='验证码']
      claim_button: button[class*='claim'], button[class*='领取']
      connect_wallet_button: button[class*='connect'], button[class*='wallet']
      submit_button: button[type='submit'], button[class*='submit']
      twitter_button: a[href*='twitter'], a[href*='x.com']
      wallet_address_input: input[placeholder*='address'], input[type='text']
    url: https://hub.0g.ai/faucet
logging:
  backup_count: 5
  console_enabled: true
  file_enabled: true
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10MB
proxy:
  enabled: false
  host: ''
  password: ''
  port: 0
  proxy_type: http
  username: ''
